export const OPENAI_API_KEY_CONFIG_KEY = 'OPENAI_API_KEY';
export const OPENAI_MODEL_CONFIG_KEY = 'OPENAI_MODEL';
export const OPENAI_UTILITY_MODEL_CONFIG_KEY = 'OPENAI_UTILITY_MODEL';
export const OPENAI_ANSWER_TIMEOUT_MS_CONFIG_KEY =
  'OPENAI_ANSWER_TIMEOUT_MS';
export const OPENAI_QUERY_REWRITE_TIMEOUT_MS_CONFIG_KEY =
  'OPENAI_QUERY_REWRITE_TIMEOUT_MS';
export const OPENAI_SUGGESTION_TIMEOUT_MS_CONFIG_KEY =
  'OPENAI_SUGGESTION_TIMEOUT_MS';

export const DEFAULT_OPENAI_MODEL = 'gpt-5-mini';
export const DEFAULT_OPENAI_UTILITY_MODEL = DEFAULT_OPENAI_MODEL;
export const DEFAULT_OPENAI_ANSWER_TIMEOUT_MS = 16000;
export const DEFAULT_OPENAI_QUERY_REWRITE_TIMEOUT_MS = 6000;
export const DEFAULT_OPENAI_SUGGESTION_TIMEOUT_MS = 15000;
