export const OPENAI_API_KEY_CONFIG_KEY = 'OPENAI_API_KEY';
export const OPENAI_MODEL_CONFIG_KEY = 'OPENAI_MODEL';
export const OPENAI_UTILITY_MODEL_CONFIG_KEY = 'OPENAI_UTILITY_MODEL';
export const OPENAI_ANSWER_TIMEOUT_MS_CONFIG_KEY =
  'OPENAI_ANSWER_TIMEOUT_MS';
export const OPENAI_QUERY_REWRITE_TIMEOUT_MS_CONFIG_KEY =
  'OPENAI_QUERY_REWRITE_TIMEOUT_MS';
export const OPENAI_SUGGESTION_TIMEOUT_MS_CONFIG_KEY =
  'OPENAI_SUGGESTION_TIMEOUT_MS';

export const DEFAULT_OPENAI_MODEL = 'gpt-4o-mini';
export const DEFAULT_OPENAI_UTILITY_MODEL = 'gpt-4o-mini';
export const DEFAULT_OPENAI_ANSWER_TIMEOUT_MS = 16000;
export const DEFAULT_OPENAI_QUERY_REWRITE_TIMEOUT_MS = 6000;
export const DEFAULT_OPENAI_SUGGESTION_TIMEOUT_MS = 15000;

export const AI_PROVIDER_CONFIG_KEY = 'AI_PROVIDER';
export const DEFAULT_AI_PROVIDER = 'openai';

export const GROQ_API_KEY_CONFIG_KEY = 'GROQ_API_KEY';
export const GROQ_MODEL_CONFIG_KEY = 'GROQ_MODEL';
export const GROQ_UTILITY_MODEL_CONFIG_KEY = 'GROQ_UTILITY_MODEL';
export const GROQ_ANSWER_TIMEOUT_MS_CONFIG_KEY =
  'GROQ_ANSWER_TIMEOUT_MS';
export const GROQ_QUERY_REWRITE_TIMEOUT_MS_CONFIG_KEY =
  'GROQ_QUERY_REWRITE_TIMEOUT_MS';
export const GROQ_SUGGESTION_TIMEOUT_MS_CONFIG_KEY =
  'GROQ_SUGGESTION_TIMEOUT_MS';

export const DEFAULT_GROQ_MODEL = 'llama-3.3-70b-versatile';
export const DEFAULT_GROQ_UTILITY_MODEL = 'llama-3.1-8b-instant';
export const DEFAULT_GROQ_ANSWER_TIMEOUT_MS = 16000;
export const DEFAULT_GROQ_QUERY_REWRITE_TIMEOUT_MS = 6000;
export const DEFAULT_GROQ_SUGGESTION_TIMEOUT_MS = 15000;
