export const AI_PROVIDER_API_KEY_CONFIG_KEY = 'AI_PROVIDER_API_KEY';
export const AI_DEFAULT_MODEL_CONFIG_KEY = 'AI_DEFAULT_MODEL';
export const AI_FAST_MODEL_CONFIG_KEY = 'AI_FAST_MODEL';
export const AI_ANSWER_TIMEOUT_MS_CONFIG_KEY = 'AI_ANSWER_TIMEOUT_MS';
export const AI_QUERY_REWRITE_TIMEOUT_MS_CONFIG_KEY =
  'AI_QUERY_REWRITE_TIMEOUT_MS';
export const AI_SUGGESTION_TIMEOUT_MS_CONFIG_KEY =
  'AI_SUGGESTION_TIMEOUT_MS';

export const DEFAULT_AI_DEFAULT_MODEL = 'openai/gpt-oss-120b';
export const DEFAULT_AI_FAST_MODEL = 'openai/gpt-oss-20b';
export const DEFAULT_AI_ANSWER_TIMEOUT_MS = 16000;
export const DEFAULT_AI_QUERY_REWRITE_TIMEOUT_MS = 6000;
export const DEFAULT_AI_SUGGESTION_TIMEOUT_MS = 15000;
